version: '3'
services:
  broker:
    build: broker
    ports:
      - "8083:8083"
  auldfellas:
    environment:
      NAME: auldfellas
    build: auldfellas
    depends_on:
      - broker
    ports:
      - "8080:8080"
  dodgygeezers:
    environment:
      NAME: dodgygeezers
    build: dodgygeezers
    depends_on:
      - broker
    ports:
      - "8082:8082"
  girlsallowed:
    environment:
      NAME: girlsallowed
    build: girlsallowed
    depends_on:
      - broker
    ports:
      - "8081:8081"